Feature yamaoka
yusuke-aoki-devpg/task-list pull request #2
Opened 2021-03-28 10:06 UTC by ymktmk

2021-03-28 15:57 UTC, ymktmk commented
/home ボールの表示
/todos リストの表示
/todos/create タスクの作成

2021-03-29 00:44 UTC, wathi requested changes

2021-03-29 00:44 UTC, wathi commented on public/js/home.js
> -}
画面サイズ変更する時、ボール自動書き換えは要らないですか？

2021-03-29 00:44 UTC, wathi commented on resources/views/todos/edit.blade.php
> +
headerとnavbarはlayoutと合体する方が管理しやすいと思います。

2021-03-29 01:03 UTC, wathi requested changes

2021-03-29 01:03 UTC, wathi commented on app/Http/Controllers/HomeController.php
> -            ->where('deadline', '<=', $d7DaysLater)
homeは７日間のtaskのみなので、この行も追加して欲しいです。

2021-03-29 03:33 UTC, ymktmk commented on public/js/home.js
> -}
あっていいと思います！

2021-03-29 03:34 UTC, ymktmk commented on resources/views/todos/edit.blade.php
> +
そうですねわかりました。

2021-03-29 03:35 UTC, ymktmk commented on app/Http/Controllers/HomeController.php
> -            ->where('deadline', '<=', $d7DaysLater)
確かにわかりました。

2021-03-29 03:54 UTC, closed without merging